Charm default to app name
canonical/gunicorn-k8s-operator pull request #23
Opened 2022-10-24 12:55 UTC by gtrkiller

This PR aims to change the default value of the external_hostname config value to an empty string, and add code to make it default to the app name when the string is empty.

2022-10-24 13:00 UTC, arturo-seijas commented on src/charm.py
> +    def _check_external_hostname(self, hostname):
The method name seems a bit ambiguous. I wouldn't expect it to return a value. Can you rename it?

2022-10-24 13:12 UTC, merkata approved these changes
Looks good! Approving.

2022-10-24 13:24 UTC, arturo-seijas approved these changes
LGTM

2022-10-24 16:00 UTC, mthaddon requested changes
Some comments inline, but can we also update the README - it currently says:
"""
Once the deployment has completed and the "gunicorn-k8s" workload state in
`juju status` has changed to "active" you can visit `http://gunicorn` in
a browser (assuming `gunicorn` resolves to the IP(s) of your k8s ingress) or the juju unit's
(gunicorn-k8s) assigned IP, and you'll be presented with a screen
that details all the environment variables used by the deployed docker image.
"""
The actual hostname in this case would be `gunicorn-k8s` not `gunicorn`.

2022-10-24 16:00 UTC, mthaddon commented on config.yaml
>      description: "External hostname this gunicorn app should respond to (required)."
Can we update the description to say if left blank the deployed juju application name will be used?

2022-10-24 16:00 UTC, mthaddon commented on src/charm.py
> +    def _assign_external_hostname(self, hostname) -> str:
I think the name of `_get_external_hostname` would be more consistent with other methods in this charm. Also, you can access `self.config` here too, which would simplify calls to this function by not needing to pass a parameter, so I think that's a better option. Also, Can you include a docstring?

2022-10-25 07:15 UTC, arturo-seijas commented on config.yaml
> +      External hostname this gunicorn app should respond to (required).
Shouldn't we remove "required" here?

2022-10-25 07:17 UTC, arturo-seijas approved these changes
LGTM

2022-10-25 07:48 UTC, mthaddon approved these changes
LGTM, thx

2022-10-25 07:48 UTC, arturo-seijas approved these changes
LGTM

2022-10-25 07:49 UTC, merged